baseURL = 'https://kliwn.dev'
languageCode = 'en-us'
title = 'Keanu Liwongan'
theme="archie"
copyright = "© Keanu Liwongan"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourDisqusShortname"

[pagination]
  pagerSize = 3 # articles per page

[params]
	# mode="auto" # color-mode → light,dark,toggle or auto
  mode = "toggle"
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "My personal website, [obviously](https://www.youtube.com/watch?v=dQw4w9WgXcQ)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
  customcss = ["css/custom.css"]
  [params.author]
      email = 'keanu.liwongan@gmail.com'
      name = 'Keanu Liwongan'

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kliwongan"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/kliwongan"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'